services:
  nginx:
    image: nginx:1.27-alpine
    container_name: weconnect-nginx-prod
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - weconnect-network
    depends_on:
      app:
        condition: service_healthy
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: weconnect-app-prod
    restart: unless-stopped
    secrets:
      - db_password
    env_file:
      - .env # Load application config from .env file
    environment:
      # Override hosts for Docker's internal network
      DB_HOST: postgres
      REDIS_HOST: redis
      # Point to the secret file for the password
      DB_PASSWORD_FILE: /run/secrets/db_password
    networks:
      - weconnect-network
    healthcheck:
      test: 'node -e "require(''http'').get(''http://localhost:3000'', { timeout: 2000 }, (res) => res.statusCode === 200 ? process.exit(0) : process.exit(1)).on(''error'', () => process.exit(1))"'
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 15s
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    container_name: weconnect-postgres-prod
    secrets:
      - db_password
    environment:
      POSTGRES_DB: weconnect
      POSTGRES_USER: weconnect
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - weconnect-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U weconnect -d weconnect']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: weconnect-redis-prod
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - weconnect-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  weconnect-network:
    driver: bridge

secrets:
  db_password:
    file: ./secrets/db_password.txt
