version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: weconnect-app
    env_file:
      - .env.prod
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    networks:
      - weconnect-network

  postgres:
    image: postgres:15-alpine
    container_name: weconnect-postgres
    env_file:
      - .env.prod
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - weconnect-network

  redis:
    image: redis:7-alpine
    container_name: weconnect-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - weconnect-network
    command: [ "redis-server", "--appendonly", "yes" ]

  arena:
    image: mixmaxhq/arena
    container_name: weconnect-arena
    ports:
      - "4567:4567"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
    depends_on:
      - redis
    networks:
      - weconnect-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  weconnect-network:
    driver: bridge
