services:
  app:
    build:
      target: development
    container_name: weconnect-app-dev
    ports:
      - '3000:3000'
      - '9229:9229' # Debug port
    volumes:
      - .:/app
      - /app/node_modules # Isolate node_modules
    command: npm run start:dev
    healthcheck:
      disable: true # Disable healthcheck for dev

  postgres:
    container_name: weconnect-postgres-dev
    ports:
      - '5433:5432'

  redis:
    container_name: weconnect-redis-dev
    ports:
      - '6380:6379'

  # GUI for PostgreSQL in development
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: weconnect-pgadmin-dev
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8080:80'
    networks:
      - weconnect-network
    depends_on:
      - postgres

  # GUI for Redis in development
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: weconnect-redis-gui-dev
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - '8081:8081'
    networks:
      - weconnect-network
    depends_on:
      - redis
